nginx:
    image: 'bitnami/nginx'
    ports:
        - '8001:8080'
    links:
        - phpfpm
    volumes:
        - ./logs/access.log:/opt/bitnami/nginx/logs/myapp-access.log
        - ./logs/error.log:/opt/bitnami/nginx/logs/myapp-error.log
        - ./nginx/app.conf:/bitnami/nginx/conf/vhosts/myapp.conf
        - ./public:/app
phpfpm:
    image: 'bitnami/php-fpm'
    ports:
        - '9001:9090'
    volumes:
        - ./public:/app